### ISSUE TITLE
remove the zero-length results from Q2

### ISSUE THREAD

**Issue by andrewsu** [andrewsu/neo4j-to-reasoner#2]
For example, "BUTYLSCOPOLAMINE - Abdominal Pain" has zero results.  Should be removed from the results list.  I will remove these files from the transferred files.

**Comment by andrewsu** [comment]
new files are uploading to dropbox now, both to remove zero length files and to update results to the latest filtering criteria (to match the live neo4j queries)...

**Comment by newgene** [comment]
updated in ba3a4b80969d304957c283f894556e83f99b6b32.
